# all time units are in seconds

# show or hide cursor
hideCursor: true

# stop propagation of all types of mouse events at document.body
disableMouseEvents: false

# disable console logging
disableConsoleLogging: false

# disable scrolling
disableScrolling: false

# variables subject to (automatic) page reload
fadeinOnLoadDelay: 1
reloadDelay: 10800
idleDelay: 15
reloadButtonSize: 40px
reloadButtonHoldTime: 5
reloadOnErrorDelay: -1

# variables subject to sliders
autoSlideDelay: 180
appRestartDelay: 10
disableBulletNavigation: true

# which page to use for the animation in the background (runs in an iframe)
# currently available: bgWebgl.html, bgSvg.html, bgPlain.html
backgroundAnimationUrl: bg_svg.html

# touch overlay debugging features
debuggingEnabled: false
debugCursorScale: 1

# touch cursor visualization
touchCursorVisible: true
touchCursorHtml: '<svg width="21" height="21" style="transform: translate(-50%, -50%);"><circle cx="11" cy="11" r="9" stroke="white" stroke-width="3.5" fill="none" /><circle cx="11" cy="11" r="9" stroke="black" stroke-width="1" fill="#ff9999" /></svg>'

# credits for the slider and the apps
credits: 'Station entwickelt von IMAGINARY (www.imaginary.org)<br />und Jürgen Richter-Gebert (www.science-to-touch.com)'

# ISO date string for whenzel config overrides. Will be used in place of actual date if supplied.
# today: '2019-05-27'

# URLs to the files that contain the messages of the day, anniversaries and announcements (JSON or YAML format)
messagesUrl: mathematikon/messages-of-the-day.yaml
anniversaryMessagesUrl: mathematikon/anniversary-messages.yaml
announcementsUrl: mathematikon/announcements.yaml
anniversaryAnnouncementsUrl: mathematikon/anniversary-announcements.yaml

# variables subject to the display of announcements
announcementDelay: 210
# additional Whenzel filterable settings for the display of announcements
announcementSettingsUrl: common/announcementSettings.yaml

apps:
  - - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/2048/Game2048App.js
    - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/surfer/SurferApp.js
    - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/ifs/IFSApp.js
    - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/sphere-chaos/SphereChaosApp.js
    - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/space-rescue/SpaceApp.js
    - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/double-pendulum/DoublePendulumApp.js
    - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/polytope-morpher/PolytopeMorpherApp.js
  - - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/car-park/CarParkApp.js
    - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/image-spiral/ImageSpiralApp.js
    - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/solitaire/SolitaireApp.js
    - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/kaleidoscope/KaleidoscopeApp.js
    - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/swarm/SwarmApp.js
    - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/iornament/iOrnamentApp.js

common:
  - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/common/js/Cindy.js
  - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/common/js/Cindy3D.js
  - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/common/js/CindyGL.js
  - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/common/js/QuickHull3D.js
  - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/common/js/katex-plugin.js
  - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/6e7678482f043db48ffc864e9c4626a33ea3490d/common/js/symbolic.js
