<div class="app">
    <object type="text/html" data="http://science-to-touch.com/Mathematikon/dmweb/content/G4/Widget.html" style="width: 100%; height: 100%;" ></object>
</div>
<div class="app_description">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</div>
<div class="app_name">App1</div>
<div class="app_credits">Author 1a<br/>Author 1b</div>
