<div class="app">
    <object type="text/html" data="http://science-to-touch.com/CJS/test/science/cindygl-demo/06_raytracer_bisection.html" style="width: 100%; height: 100%;" ></object>
    <script>
        current_content_slides.push(
            new function () {
                return {
                    pause: function() { console.log( 'pause app2' ); },
                    resume: function() { console.log( 'resume app2' ); },
                    restart: function() { console.log( 'restart app2' ); }
                }
            }
        );
    </script>
</div>
<div class="app_description">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</div>
<div class="app_name">App2</div>
<div class="app_credits">Author 2a<br/>Author 2b</div>
