<div class="app">
    <script src="content/canvas-paint.js"></script>
</div>
<div class="app_description">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</div>
<div class="app_name">App2</div>
<div class="app_credits">Author 2a<br/>Author 2b</div>
