# all time units are in seconds

# show or hide cursor
hideCursor: true

# stop propagation of all types of mouse events at document.body
disableMouseEvents: true

# disable console logging
disableConsoleLogging: false

# disable scrolling
disableScrolling: true

# variables subject to (automatic) page reload
fadeinOnLoadDelay: 1
reloadDelay: 10800
idleDelay: 15
reloadButtonSize: 40px
reloadButtonHoldTime: 5

# variables subject to sliders
autoSlideDelay: 180
appRestartDelay: 10

# variables subject to heartbeat
heartbeatEnabled: true
heartbeatInterval: 2
heartbeatUrl: http://localhost:8081/heartbeat

# which page to use for the animation in the background (runs in an iframe)
# currently available: bgWebgl.html, bgSvg.html, bgPlain.html
backgroundAnimationUrl: bg_plain.html

# touch overlay debugging features
debuggingEnabled: true
debugCursorScale: 1

# touch cursor visualization
touchCursorVisible: true
touchCursorHtml: '<svg width="21" height="21" style="transform: translate(-50%, -50%);"><circle cx="11" cy="11" r="9" stroke="white" stroke-width="3.5" fill="none" /><circle cx="11" cy="11" r="9" stroke="black" stroke-width="1" fill="red" /></svg>'

apps:
  - - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/0549fa0dcc316b2dc236d0fd1e32e61e3712397f/testing-counter/CounterApp.js
    - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/0549fa0dcc316b2dc236d0fd1e32e61e3712397f/testing-object/RaytracerApp.js
    - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/0549fa0dcc316b2dc236d0fd1e32e61e3712397f/testing-iframe/CarParkIFrameApp.js
    - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/0549fa0dcc316b2dc236d0fd1e32e61e3712397f/testing-multitouch-paint/PaintApp.js
  - - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/0549fa0dcc316b2dc236d0fd1e32e61e3712397f/testing-multitouch-paint/PaintApp.js
    - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/0549fa0dcc316b2dc236d0fd1e32e61e3712397f/testing-counter/CounterApp.js
    - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/0549fa0dcc316b2dc236d0fd1e32e61e3712397f/testing-counter/CounterApp.js

common:
  - https://rawcdn.githack.com/IMAGINARY/content-slider-apps/0549fa0dcc316b2dc236d0fd1e32e61e3712397f/common/noop.js
