<?php
/******************************
 * BEGIN configuration
 ******************************/
// all time units are in seconds

// variables subject to automatic page reload
$fadein_on_load_delay = 15;
$reload_delay = 3 * 60 * 60;
$idle_delay = 15;

// variables subject to sliders
$auto_slide_delay = 3 * 60;
$app_restart_delay = 10;

// variables subject to heartbeat
$heartbeat_interval = 2;
$heartbeat_url = 'http://localhost:8081';

/******************************
 * END configuration
 ******************************/
 ?>
